---
- name: Converge
  hosts: all
  roles:
    - role: datagov-deploy-pycsw
      datagov_in_service: false
      pycsw_db_host: localhost
      pycsw_db_password: fake-db-password
      pycsw_deploy_version: 20190308132800Z
