---
# Having virtualenv in python 2 and 3 simplifies things a little
- name: install virtualenv
  pip: >-
    executable={{ pycsw_python_bin }}/pip
    name=virtualenv
    state=present
    umask=0022
