---
- debug:
    msg: virtualenv_command={{ virtualenv_command }}
  when: debug is defined

- name: install app dependencies into virtualenv
  pip: >-
    virtualenv={{ pycsw_app_release_path }}/.venv
    virtualenv_command={{ pycsw_python_bin }}/virtualenv
    requirements={{ pycsw_app_release_path }}/requirements-datagov.txt
    chdir={{ pycsw_app_release_path }}
    umask=0022
    state=present
