---
# ansistrano_release_path is only registered in the update-code phase, so it is
# not available earlier.
- name: save the app release path to variable
  set_fact:
    pycsw_app_release_path: "{{ ansistrano_release_path.stdout }}"

- name: install app dependencies into virtualenv
  pip: >-
    virtualenv={{ pycsw_app_release_path }}/.venv
    virtualenv_command={{ pycsw_python_bin }}/virtualenv
    requirements={{ pycsw_app_release_path }}/requirements-datagov.txt
    chdir={{ pycsw_app_release_path }}
    umask=0022
    state=present
