---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    environment:
      PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/datagov-deploy-pycsw
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pipenv-{{ checksum "Pipfile.lock" }}
            - v1-pipenv-
      - run: pipenv sync --dev
      - save_cache:
          key: v1-pipenv-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - setup_remote_docker
      - run: pipenv run test

  snyk:
    docker:
      - image: circleci/python:3.6-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pipenv-{{ checksum "Pipfile.lock" }}
            - v1-pipenv-
      - run:
          name: install dependencies
          command: pipenv sync --dev
      - save_cache:
          key: v1-pipenv-{{ checksum "Pipfile.lock" }}
          paths:
            - .venv
      - run: sudo npm install -g snyk
      - run: snyk test


workflows:
  version: 2
  commit:
    jobs:
      - build
      - snyk
