---
- name: Converge
  hosts: all
  roles:
    - role: datagov-deploy-pycsw
      pycsw_db_host: localhost
      pycsw_db_password: fake-db-password
      pycsw_deploy_version: 20190308132800Z
      pycsw_python_version: 3.6.12  # 3.6.x is the latest python3 that will build with our version of openssl
